name: qspy
channels:
  - conda-forge
  - alubbock
  - defaults
dependencies:
  - appdirs=1.4.4
  - astropy=5.3.4
  - bionetgen=2.5.1
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - cython=0.29.33
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.39
  - libtiff=4.5.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - networkx=2.8.4
  - nfsim=1.12.1
  - nodejs=20.8.0
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=3.0.13
  - packaging=23.2
  - pcre=8.45
  - perl=5.32.1.1
  - pillow=9.4.0
  - ply=3.11
  - pooch=1.4.0
  - pycparser=2.21
  - pyerfa=2.0.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysb=1.15.0
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.8.2
  - pyyaml=6.0.1
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - scipy=1.10.1
  - setuptools=66.0.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - toml=0.10.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.0
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.13.0
      - backcall==0.2.0
      - backrefs==5.8
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.0
      - click==8.2.1
      - colorama==0.4.6
      - comm==0.1.4
      - coverage==7.6.10
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docstring-parser==0.16
      - executing==2.0.0
      - fastjsonschema==2.18.1
      - fqdn==1.5.1
      - ghp-import==2.1.0
      - griffe==1.7.3
      - iniconfig==2.0.0
      - ipykernel==6.25.2
      - ipython==8.16.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.1
      - jupyter-core==5.3.2
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.6
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - jupyterlab-widgets==3.0.9
      - markdown==3.8
      - markupsafe==2.1.3
      - matplotlib-inline==0.1.6
      - mergedeep==1.3.4
      - mergram==0.3.0
      - microbench==0.9.1
      - mistune==3.0.2
      - mkdocs==1.6.1
      - mkdocs-autorefs==1.4.2
      - mkdocs-get-deps==0.2.0
      - mkdocs-material==9.6.14
      - mkdocs-material-extensions==1.3.1
      - mkdocstrings==0.29.1
      - mkdocstrings-python==1.16.11
      - nbclassic==0.5.6
      - nbclient==0.8.0
      - nbconvert==7.9.2
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - nose==1.3.7
      - notebook-shim==0.2.3
      - overrides==7.4.0
      - paginate==0.5.7
      - pandas==2.3.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathspec==0.12.1
      - pickleshare==0.7.5
      - pip==25.1.1
      - platformdirs==3.11.0
      - pluggy==1.5.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - psutil==5.9.5
      - pubchempy==1.0.4
      - pure-eval==0.2.2
      - pygments==2.16.1
      - pymdown-extensions==10.15
      - pyrsistent==0.19.3
      - pysb-pkpd==0.5.3
      - pysb-units==0.4.1
      - pytest==8.3.4
      - python-json-logger==2.0.7
      - python-louvain==0.16
      - pytkdocs==0.16.5
      - pytz==2025.2
      - pyvipr==1.0.7
      - pywin32==306
      - pywinpty==2.0.12
      - pyyaml-env-tag==1.1
      - pyzmq==25.1.1
      - referencing==0.30.2
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.4
      - seaborn==0.13.2
      - send2trash==1.8.2
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - terminado==0.17.1
      - tinycss2==1.2.1
      - tornado==6.3.3
      - traitlets==5.11.2
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.6.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.0.6
      - watchdog==6.0.0
      - wcwidth==0.2.8
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - widgetsnbextension==4.0.9