site_name: QSPy

theme:
  name: "material"

plugins:
  - search # support for search bar
  - mkdocstrings: # mkdocstrings - needed for making docs entries from docstrings
      handlers:
          python:
              options:
                  docstring_style: numpy
              paths: [qspy]  # search packages in the src folder

markdown_extensions:
  - attr_list
  # emoji rendering using emoji shortcodes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

# math rendering using Mathjax
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Home: index.md
  - User Guide:
    - Model Components: model-components.md
    - Model Specification: model-specification.md 
    - Functional Tags: functional-tags.md
    - Model Checker: model-checker.md
    - Metadata Tracking: metadata-tracking.md
    - Model Summary Generator: model-summary-generator.md
    - How-To Guides: how-to-guides.md
    - Tutorials: tutorials.md
    - API Reference: reference.md
  - About:
    - License: license.md
    - Contributing: contributing.md
    - Citing: citing.md
    - Supporting: supporting.md
    - Source Code: https://github.com/Borealis-BioModeling/qspy
  - Resources:
      - What is QSP Modeling: qsp-modeling.md
      - Related Software: related-software.md
  - Contact/Support: contact-support.md
